project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "R4SIPS"
  subtitle: "An Introduction to R programming for SI Physiology"
  author: "Kittipos Sirivongrungson"
  cover-image: "images/cover.png"
  site-url: https://r4sips.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r4sips
  repo-branch: master
  repo-actions: [edit]
  #downloads: pdf
  chapters:
    - index.qmd
    - part: "Setup"
      chapters:
      - "contents/install.qmd"
      - "contents/rstudio.qmd"
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc-depth: 3
    code-overflow: scroll
    code-tools: true
    code-link: true
  #pdf:
    #documentclass: scrreprt
    #toc-depth: 3


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto