project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "R for SIPS"
  subtitle: "Introduction to R programming"
  author: "กิตติพศ​ ศิริวงศ์รังสรร"
  date: "4/16/2022" # `today` for current date when render
  site-url: https://r4sips.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r4sips
  #downloads: pdf
  chapters:
    - index.qmd
    - part: "Setup"
      chapters:
      - "contents/install.qmd"
    - "contents/intro.qmd"
    - "contents/summary.Rmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc-depth: 3
    code-overflow: scroll
    code-tools: true
  #pdf:
    #documentclass: scrreprt
    #toc-depth: 3


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto