project:
  type: book
  execute-dir: project # Use project root as working dir

book:
  title: "R for SI Physiology"
  subtitle: "An Introduction to R programming for SI Physiology"
  author: "Kittipos Sirivongrungson"
  cover-image: "images/cover.png"
  site-url: https://r4sips.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r4sips
  repo-branch: main
  repo-actions: [edit]
  #downloads: pdf
  chapters:
    - index.qmd
    - "contents/material.qmd"
    - part: "Setup"
      chapters:
      - "contents/install.qmd"
      - "contents/rstudio.qmd"
    - part: "Check this out"
      chapters:
      - "contents/r-resources.qmd"
      - "contents/r-tips.qmd"
      - "contents/tools.qmd"
    - references.qmd

lang: th
bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo]
      dark: superhero
    css: "assets/styles.css"
    toc-depth: 3
    code-overflow: scroll
    code-tools: true
    code-link: true
  #pdf:
    #documentclass: scrreprt
    #toc-depth: 3


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto